#+title: DnD Virtual TableTop
#+author: Максимов Матвей Алексеевич

* Краткое описание
Основная цель приложения - создать платформу, которая позволит играть в DnD с использованием внешних дисплеев. Динамическая карта, которую не надо перерисовывать.

Позже появились идеи расширить приложение до большего, чем просто вывод картинки карты. Совместно с студенческим объединением [[https://vk.com/istudnd][ДнД(НРИ) ИжГТУ]] был разработан набор [[id:be600a01-6a38-41f4-9792-a72a26b5b53c][требований]] к функционалу приложения.

* Ключевой функционал [0/8] [[#keyFunctional]]
:PROPERTIES:
:ID:       be600a01-6a38-41f4-9792-a72a26b5b53c
:END:
** TODO [#A] Добавление своих карт
Мастер должен суметь добавить любую свою карту. Работа с наиболее распространёнными форматами:
- JPG/JPEG;
- PNG;
- HEIC.
*** Перспектива
Добавление не только карт в виде картинки, но и 3D моделей. Соответственно, способность осматривать сцену с любых ракурсов или только с ракурсов игроков (от первого лица).
** TODO [#A] Передвижение персонажей по карте
Игроки смогут передвигать своих персонажей, а приложение будет параллельно показывать максимальную оставшуюся дальность передвижения. Мастер сможет принудительно перемещать игроков и NPC.
** TODO [#E] Линейка для измерения расстояний
Измерение расстояний между клетками. В том числе по диагонали. Результат должен округляться в ближайшую сторону до целого числа.
*** Перспектива
Можно учитывать скорость персонажа в дробных числах, что приблизит к реалистичности. Игроку будет выводиться дробное значение на его экране, так что считать это не придётся.
** TODO [#C] Импорт листов персонажа
Возможность импортировать лист персонажа. Возможно:
- Создать свой генератор листов персонажа. Из плюсов, можно создать генераторы для разных систем (DnD, Sword World, FATAL, Cyberpunk RED);
- Использовать готовый вариант по типу [[https://longstoryshort.app][Long Story Short]] (тогда будет необходимо импортировать в виде CSV).
*** Перспективы
Импорт и экспорт из [[https://longstoryshort.app][Long Story Short]] в CSV формате.
** TODO [#C] Сетевая связь
Синхронизация нескольких устройств в одной локальной сети. Скорее всего будет реализовано в виде связи через между устройствами через Qt и передача производимых действий.
Для мастера:
- Отображение всего
- Отсутствие тумана войны
- Полные привилегии
Для игрока:
- Отображение только своей части интерфейса
- Туман войны
** TODO [#D] Сетка карты
Отдельная программная сетка поверх карты. Будет создаваться мастером при добавлении карты указанием размерности в соответствуюшем окошке.
** TODO [#E] Туман войны
Добавление для игроков тумана войны. Мастер при добавлении карты отмечает препятствия, через которые игроки не смогут видеть и для игроков не показываются невидимые сектора. Мастеру показывается вся карта, но он может включить режим отображения Игрока (только вместо полной невидимости секторов будет накладываться полутень).

Также будут полупрозрачные клетки, объекты за которыми будет в полутени как у мастера.
*** Перспективы
Можно добавить AI, который сам сможет выделить клетки, сквозь которые можно видеть и сквозь которые нельзя видеть.
** TODO [#D] Геометрические схемы для заклинаний
Будет набор предопределённых схем заклинаний, которые можно будет наложить на поле, чтобы увидеть куда заклинание бьёт.
*** Перспективы
Также приложение сможет само рассчитывать наносимый урон, но в большинстве случаев скорее всего игрокам самим будет нужно кидать кубики, так как в игре есть слишком много различных способностей и условностей.

* Дорожная карта [0/6]
- [ ] Разработка интерфейса
- [ ] Добавление основных окон и перемещение между ними (без функционала) [0/4]
  - [ ] Главный экран
  - [ ] Добавление карт мастером
  - [ ] Экран самой игры
  - [ ] Справка
- [ ] Функционал добавления карт [0/3]
  - [ ] Добавление файла карты
  - [ ] Расстановка препятствий
  - [ ] Экспорт файла карты
- [ ] Импорт листов персонажа [0/2]
  - [ ] Редактор листов персонажа [0/5]
    - [ ] DnD 2014
    - [ ] DnD 2024
    - [ ] Sword Online
    - [ ] Cyberpunk RED
    - [ ] Возможно система расширений для добавление карт других систем
  - [ ] Импорт и экспорт json в формате [[https://longstoryshort.app][LongStoryShort]]
- [ ] Передвижение персонажей по карте [0/2]
  - [ ] Размещение персонажа на карте
  - [ ] Перемещение персонажа между клетками на карте
- [ ] Сетевой код [0/2]
  - [ ] Установление связи между устройствами
  - [ ] Передача данных между устройствами

* Сборка
** Общие требования
- *C++17 компилятор*
  - GCC ≥ 9, Clang ≥ 10, MSVC ≥ 2019
- *CMake* ≥ 3.16
- *Qt 6.5* (с компонентами: Quick, Quick Controls)
*** Mac OS
#+begin_src shell
brew install qt cmake llvm
#+end_src
*** Linux
#+begin_src shell
sudo apt update
sudo apt install build-essential cmake qt6-base-dev qt6-declarative-dev
#+end_src
*** Windows
1. Установите [[https://www.qt.io/download][Qt Online Installer]] и выберите Qt 6.5 + MinGW или MSVC.
2. Установите [[https://cmake.org/download/][CMake]] (версия ≥ 3.21).
3. Добавьте путь к =cmake= в =PATH=.
4. (Опционально) Установите =windeployqt= для деплоя приложения.
** Сборка
#+begin_src shell
cmake -S . -B build
cmake --build build
#+end_src
** Запуск
#+begin_src shell
./build/src/dnd-vtt
#+end_src
